version: "3.9"
services:
  mizu:
    container_name: "MizuPBX"
    build:
      context: "."
      dockerfile: "./Dockerfile"
    ports:
      - "5060:5060" # SIP server port
      - "80:80"  # Mizu API
      - "8080:8080" # NoVnc Port
      - "5900:5900" # VNC Port
    network_mode: "host" # this is best as there is no need for forwarding VOIP ports
